export default {
  TOP_LEFT: Symbol('TOP_LEFT'),
  TOP_MIDDLE: Symbol('TOP_MIDDLE'),
  TOP_RIGHT: Symbol('TOP_RIGHT'),
  MIDDLE_LEFT: Symbol('MIDDLE_LEFT'),
  MIDDLE_CENTER: Symbol('MIDDLE_CENTER'),
  MIDDLE_RIGHT: Symbol('MIDDLE_RIGHT'),
  BOTTOM_LEFT: Symbol('BOTTOM_LEFT'),
  BOTTOM_CENTER: Symbol('BOTTOM_CENTER'),
  BOTTOM_RIGHT: Symbol('BOTTOM_RIGHT')
};
